const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const {load,validate} = require('../scripts/validate-bank.cjs');
const root = path.resolve(__dirname,'..');
function app() {
 const data = new Map(), nodes = new Map();
 const html = fs.readFileSync(path.join(root,'index.html'),'utf8');
 for(const [,id] of html.matchAll(/id="([^"]+)"/g)) nodes.set(id, {
  innerHTML:'',textContent:'',value:'all',style:{},className:'',
  classList:{add(){},remove(){},toggle(){},contains(){return false}},
  addEventListener(){},setAttribute(){},scrollIntoView(){},querySelectorAll(){return []}
 });
 const get=id=>{
  // Some practice/bank nodes are generated by innerHTML.
  if(!nodes.has(id)) nodes.set(id,{innerHTML:'',textContent:'',value:'',style:{},classList:{add(){},remove(){}},setAttribute(){}});
  return nodes.get(id);
 };
 const document={getElementById:get,querySelectorAll(){return []},addEventListener(){},body:{className:'theme-dark'}};
 const window={addEventListener(){},scrollTo(){}};
 const localStorage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k)};
 const ctx={window,document,localStorage,console:{log(){}},setInterval:()=>1,clearInterval(){},alert:message=>{throw Error(message)},confirm:()=>true};
 for(const [,src] of html.matchAll(/<script src="([^"]+)"/g)) vm.runInNewContext(fs.readFileSync(path.join(root,src),'utf8'),ctx,{filename:src});
 get('bankSearchInput').value='';get('practiceElementSelect').value='1';get('practiceCountSelect').value='10';
 return {window,data,get};
}
test('bank counts, all outcomes and duplicate guard',()=>{
 const w=load(), result=validate(w);
 assert.equal(result.total,193);assert.equal(result.errors.length,0);assert.equal(result.warnings.length,0);
 for(const e of w.CIRE_MANIFEST.elements)for(const s of e.subOutcomes)assert.ok(w['CIRE_QUESTIONS_E'+e.id].some(q=>q.subOutcome===s.code&&q.provenance==='original-2026-09'));
 const q=w.CIRE_QUESTIONS_E1[0];
 w.CIRE_QUESTIONS_E1.push({...q,id:'DUP',question:'Case study with a new name: '+q.question});
 assert.ok(validate(w).errors.some(e=>e.includes('Repeated wrapped question')));
});
test('all legacy option permutations map to the unchanged canonical answer',()=>{
 const {window:w}=app();
 for(const [oldId,a] of Object.entries(w.CIRE_QUESTION_ALIASES)) {
  for(let selected=0;selected<4;selected++) {
   const result=w.CIRE_QUESTION_BANK.answers({[oldId]:{selected,isCorrect:false,timestamp:1}})[a.id];
   assert.equal(result.selected,a.options[selected]);
   assert.equal(result.isCorrect,a.options[selected]===w.CIRE_QUESTION_BANK.byId.get(a.id).correct);
  }
 }
});
test('newest duplicate answer wins and removed or malformed progress does not count',()=>{
 const {window:w}=app();const [oldId,a]=Object.entries(w.CIRE_QUESTION_ALIASES)[0];
 const selected=w.CIRE_QUESTION_BANK.byId.get(a.id).correct;
 const result=w.CIRE_QUESTION_BANK.answers({[oldId]:{selected:0,timestamp:1},[a.id]:{selected,timestamp:2},'CIRE-E1-004':{selected:0,timestamp:3},bad:{selected:99}});
 assert.equal(Object.keys(result).length,1);assert.equal(result[a.id].isCorrect,true);
 assert.equal(Object.keys(w.CIRE_QUESTION_BANK.answers(null)).length,0);
});
test('flags and flashcards migrate and can be cleared without alias resurrection',()=>{
 const {window:w,data}=app();const [oldId,a]=Object.entries(w.CIRE_QUESTION_ALIASES)[0];
 data.set('cire_flagged_v1',JSON.stringify([oldId,a.id,'CIRE-E1-004']));
 assert.equal(w.CIRE_STORAGE.getFlagged().size,1);
 w.CIRE_STORAGE.toggleFlag(a.id);assert.equal(w.CIRE_STORAGE.getFlagged().size,0);
 assert.ok(JSON.parse(data.get('cire_flagged_v1')).includes('CIRE-E1-004'));
 data.set('cire_flashcards_v1',JSON.stringify({[oldId]:'review','CIRE-E1-004':'review'}));
 w.CIRE_STORAGE.setFlashcardRating(a.id,'mastered');
 assert.equal(w.CIRE_STORAGE.getFlashcardReviews()[a.id],'mastered');
 assert.equal(Object.keys(w.CIRE_STORAGE.getFlashcardReviews()).length,1);
});
test('saving a current answer preserves raw retired records for backups',()=>{
 const {window:w,data}=app();const q=w.CIRE_QUESTION_BANK.questions[0];
 data.set('cire_answers_v1',JSON.stringify({'CIRE-E1-004':{selected:0,timestamp:1}}));
 w.CIRE_STORAGE.saveAnswer(q.id,q.correct,true);
 assert.ok(JSON.parse(data.get('cire_answers_v1'))['CIRE-E1-004']);
 assert.equal(Object.keys(w.CIRE_STORAGE.getAnswers()).length,1);
});
test('dashboard, explorer, topic practice and flashcards load the active bank',()=>{
 const {window:w,get}=app();w.CIRE_APP.init();
 assert.equal(get('headerProgressText').textContent,'0 / 193');
 assert.equal(get('statRemaining').textContent,'193 remaining');
 assert.match(get('bankElementFilter').innerHTML,/193 Questions/);
 assert.match(get('cardCounterText').textContent,/\/ 193$/);
 get('practiceSubOutcomeSelect').value='1.6';w.CIRE_APP.startTopicSession();
 assert.match(get('practiceQuestionCard').innerHTML,/CIPF/);
 assert.match(get('practiceQuestionCard').innerHTML,/Study references/);
 w.CIRE_APP.answerTopicQuestion(0);
 assert.equal(Object.keys(w.CIRE_STORAGE.getAnswers()).length,1);
 get('bankSearchInput').value='daily 2x';w.CIRE_BANK.search();
 assert.match(get('bankResultsCount').textContent,/of 1 questions/);
});
test('mock exams contain 110 distinct questions with the prescribed weights and grade correctly',()=>{
 const {window:w,get}=app();
 for(let round=0;round<3;round++) {
  const seen=new Set(),counts={};w.CIRE_EXAM.startExam();
  assert.equal(get('examTimerDisplay').textContent,'02:00:00');
  for(let i=0;i<110;i++) {
   w.CIRE_EXAM.jumpTo(i);
   const stem=get('examQText').textContent;
   assert.ok(!seen.has(stem));seen.add(stem);
   const q=w.CIRE_QUESTION_BANK.questions.find(q=>q.question===stem);
   counts[q.element]=(counts[q.element]||0)+1;
   w.CIRE_EXAM.selectOption(q.correct);
  }
  for(const e of w.CIRE_MANIFEST.elements)assert.equal(counts[e.id],e.examWeight);
  w.CIRE_EXAM.finalizeSubmit();
  assert.equal(get('resScoreText').textContent,'110 / 110');
  assert.equal(w.CIRE_STORAGE.getMockHistory()[0].percentage,100);
  w.CIRE_EXAM.filterReview('all');assert.match(get('resultsReviewList').innerHTML,/Study references/);
 }
});
test('worked examples have correct independently calculated numerical answers',()=>{
 const {window:w}=app();
 const cases=[[/A \$20,000 account/,((20000*0.06-300)/20000*100)+'%.'],[/price index rises/,((130-125)/125*100)+'%.'],[/200 shares at \$24/,'$'+(200*24+12).toLocaleString('en-US')+'.'],[/assets of \$52 million/,'$'+((52000000-2000000)/5000000)+'.'],[/daily 2x leveraged ETF starts/,'$'+Math.round(100*1.2*0.8)+'.']];
 for(const [pattern,expected] of cases){const q=w.CIRE_QUESTION_BANK.questions.find(q=>pattern.test(q.question));assert.ok(q,String(pattern));assert.equal(q.options[q.correct],expected);}
});
test('explanations escape content and render only valid referenced sources',()=>{
 const {window:w}=app();
 const html=w.CIRE_QUESTION_BANK.explanationHTML({explanation:'<img onerror="bad">',references:['syllabus','missing']});
 assert.ok(!html.includes('<img'));assert.ok(html.includes('&lt;img'));assert.ok(html.includes('rel="noopener noreferrer"'));
});
